In [19]:
import pandas as pd
contrib = pd.read_csv("financial_contributions.csv")
contrib
contrib[['Date', 'Nume Prenume', 'Sursa', 'Currency', 'Incasat', 'NumPers','Clasa']]

,Date,Nume Prenume,Sursa,Currency,Incasat,NumPers,Clasa
0,23-05-2023,Nikolaje L Liuba 4 Adriana Cuzman,Revolut,RON,250,1,XII-D
1,15-04-2023,Sebastian Ivan,Revolut,RON,500,2,XII-D
2,18-04-2023,Ciotescu Raul,Revolut,RON,200,1,XII-D
3,18-04-2023,Danielescu Aura Codruta,BT,RON,450,2,XII-E
4,05-05-2023,Dragisa Uncul,Revolut,RON,425,2,XII-E
5,12-05-2023,Moldovan Ioana Lucia Purge,Revolut,RON,200,1,XII-F
6,15-05-2023,Flavius Ban,Revolut,RON,200,1,XII-D
7,19-05-2023,Alina Petrica,Revolut,RON,200,1,XII-D
8,19-05-2023,Silviu Stanca,Revolut,RON,400,2,XII-A
9,20-05-2023,Florentin Munteanu,Revolut,RON,200,1,XII-D
10,23-05-2023,Nikolaje L Liuba 4 Adtiana Cuzman,Revolut,RON,150,1,XII-D
11,29-05-2023,Diana Melania Beck,Revolut,RON,200,1,XII-E
12,30-05-2023,Alina Florina Baciu Toma,Revolut,RON,200,1,XII-D
13,01-06-2023,Dan Cristian Smolinschi 4 Alina Totoescu,Revolut,RON,250,1,XII-G
14,02-06-2023,Calin Costin Creanga - PROTOCOL,Revolut,RON,100,1,XII-G
15,03-06-2023,Simona Alina Cimpoesu,Revolut,RON,225,1,XII-D

In [20]:
cost_per_pers=120+20
colegi = contrib.NumPers.sum()
profesori = 10
total_px=colegi+profesori
incasat = contrib.Incasat.sum()
real_cost = total_px*cost_per_pers
spre_retur = incasat-real_cost

print(f'Persoane: {total_px} si 10 profesori')
print(f'incasat: {incasat}')
print(f'real_cost: {real_cost}')
print(f'retur: {spre_retur}')

Persoane: 30 si 10 profesori
incasat: 4150
real_cost: 4200
retur: -50

In [21]:
#todo
#1. flori scoala = 300 RON?
#2. apa scoala = 200 ron?
#3. share meniu info
#4. pay Vineri13
#5. org conf call via MS Teams